### ISSUE TITLE
Remediate Michigan Transform Script

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#117]
# Problem
We have recently updated our transform python script framework to 
make it easier to use and has far less boiler plate code. We need to migrate
the existing Michigan script to this new framework.

# Tasks
- [ ] Create a 1,000 record sample file and share in the dropbox folder. Ideally 
use resevoir sampling step from Kettle a'la src/main/pdi/NewYork/SampleNewYork.ktr
- [ ] Create the correct initializer code in 
`src/python/national_voter_file/us_states/mi/transfomer.py`. 
You can use `state_transformer_template.py` or the Florida transformer for guidance
- [ ] We now have new handling for Unparsable USAddresses. Make sure the `extract_registration_address` 
populates RAW_ADDR1, RAW_ADDR2, RAW_ZIP, and RAW_CITY. With uncleansed data straight 
from the voter file. If you are able to correcly parse the address with  USAddress
parser then set VALIDATION_STATUS to 2. Set VALIDATION_STATUS to 1 if the parser fails
and leave the Registration data fields set to None 
- [ ] delete `prepare.py`
- [ ] Test out your transformer using the sample data file and review the results.
- [ ] Update the test method in test_transformers.py and run the full nosetests

**Comment by pjsier** [comment]
Feel free to assign this to me! Should be able to make a PR by the end of the day
