### ISSUE TITLE
Refactor build scripts for local and prod

### ISSUE THREAD

**Issue by pjsier** [national-voter-file/national-voter-file#172]
# Problem

Right now we only have a few build scripts, and they're all using Docker Compose. We need to restructure these into a format similar to the us_states module (potentially build_scripts/mi.sh as an example), and also allow for toggling the environment so that prod does not use Docker and local defaults to using sample data files rather than full.

## Subtasks
- [ ] Reorganize data loading shell scripts into a format similar to the Python module
- [ ] Add an option for setting the environment for the build, and setting the files and use of Docker based on this
- [ ] Document the process to make it easy for people to add additional build scripts

**Comment by pjsier** [comment]
I can make a first pass at this in the next two days

**Comment by JakeStevens** [comment]
I've been (slowly, busy time in the semester right now) working on automating the data pipeline, which I would see as complementing this pull issue. Basically, I want a framework + scripts that will obtain and transform whatever voter files (or other data) that are available online on a weekly basis.

The data loading shell scripts could also then be scheduled weekly, check to see if there is a file to load, load it if there is, and then delete the file loaded since there is a copy of the data in the DB. Alternatively, the files of cleaned data can also be kept as some sort of backup.

**Comment by pjsier** [comment]
@JakeStevens that sounds great! Do you think splitting up the shell scripts this way will work with your ETL plan? 

Want to make sure that this won't conflict with a more comprehensive ETL setup, but now that we're starting to load data this seems like a step in the right direction.

**Comment by JakeStevens** [comment]
I think so. If there were shell scripts that I could call for data loading for each state/generic one that takes an input, then I can just call those scripts after obtaining new data

**Comment by pjsier** [comment]
Thinking more about this, in theory loading the actual state data should be the exact same every time other than specific parameters (like report date and the filename). 

The only thing that should be different between states is loading contextual information for things like electoral jurisdictions and precincts, which should theoretically be separate and only done on initial load. I'm not as familiar with those, so bringing in @BenGalewsky for context. 

Should we just make build scripts the initial seed data on things like precincts and jurisdictions, and have one generic script for calling the state transformer on a file and then loading it with Pentaho?

**Comment by JakeStevens** [comment]
Yes, I think we would need one generic script for calling the state transformer and loading a cleaned file into Pentaho. It would be nice to also have a script that only loads a transformed file into Pentaho; the scripts that I'm working on already fetches and transform state files, so I could use a script that only loads a transformed file
