### ISSUE TITLE
Spring cleaning for repo

### ISSUE THREAD

**Issue by pjsier** [national-voter-file/national-voter-file#196]
# Problem

Right now the repo structure isn't too clear for people coming into the project. We need to clean things up to make it more understandable as well as adding additional documentation

## Subtasks
- [ ] Clean up obsolete files, directories, docs
- [ ] Remove non-transformer from `national_voter_file` namespace
- [ ] Add more comprehensive, clear documentation
- [ ] Add `data` directory into version control (with all state data still gitignored) with test data back in so that it's visible for people
