### ISSUE TITLE
Data Steward Voter Roll Upload

### ISSUE THREAD

**Issue by JakeStevens** [national-voter-file/national-voter-file#210]
# Problem

Data Stewards need an easy-to-use portal for uploading voter information.  A MVP, proof of concept version of this portal should be started that allows people to upload standard voter files from the SoS for states that already exist in the database. This is assumed to be the simplest form of upload, adding a new, updated voter file. A "Data Steward" should be authorized by NVF.

## Subtasks
- [ ] Wireframe a preliminary design for web page
- [ ] Create a "Data Steward" user type in API
- [ ] Develop Python scripts/Pentaho jobs to upload voter files
- [ ] Add data to DB using above scripts after a user uploads them
- [ ] Inform user of success or give human readable error messages upon failure of upload to DB

**Comment by JoshSmith** [comment]
Would you mind clarifying who is meant by a "data steward" here, ideally with some examples?

**Comment by JakeStevens** [comment]
I could imagine two different groups of people:
1.) Somebody directly working for NVF. For example, I personally take responsibility for Indiana and want to purchase and upload the voter file every year. Ideally, there should be some way of doing so without directly ssh'ing to a server.
2.) A group working with/using NVF. For example, see the conversation between Ben and Jeremy regarding an organization uploading its own data as a new "reporter"

**Comment by JoshSmith** [comment]
Understand and absolutely agree with #1.

**Comment by JoshSmith** [comment]
Can you add some context from 2 into this thread @JakeStevens?

**Comment by JakeStevens** [comment]
J:
question: how often do you update the voter files after getting them?
i'm guessing it varies by state

B:
Our plan is to find someone to curate each state. Certainly once a month is a good target. Near an election we may want more frequently to capture new registrations

J:
woohoo! once a month is perfect for our needs. with our web app, we'll also have real-time updates rolling constantly, which we could or could not integrate into your larger voter file

B:
Our model would accomodate updates. Generally speaking with a data warehouse, we'd want to do batch updates from your data.. maybe overnight, but it could be more frequent
We'd make you a "reporter" so we could compare data reported by you to data reported by the secty of state

J:
that's great. we're going to have various security mechanisms in place to ensure data isn't purposely corrupted. some of these securities will, at least at first, require manual review of each update submitted by a caller so batches work great, bc it'll take time for us to review each submission

**Comment by BenGalewsky** [comment]
The action behind the scene is to upload to a state-specific S3 bucket. We can set up basic auth credentials to accommodate this. The S3 API has a fine POST interface.
