### ISSUE TITLE
Build ETL Docker Image 

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#216]
# Problem

The docker image for the ETL container is built locally and mounts the user's git repo as a volume. This is great for development, but can't be used for running jobs in AWS batch. We would like to set up a webhook in dockerhub that will watch for commits to the repo and automatically build and publish a new docker image.

## Subtasks
- [ ] Create a version of the Dockerfile that copies the entire src tree into the docker FS (include loader too)
- [ ] Use docker environment variables to allow users to specify the database Host, user, and password to be used. This will have to be folded into `/opt/pentaho/data-integration/simple-jndi` so that the Voter JNDI name will point to the desired DB
- [ ] Create a nationalvoterfile docker hub account
- [ ] Create a web hook from our github repo to automatically build when new commit to master

## References

Progress on: #

**Comment by BenGalewsky** [comment]
Just about have this done. Still need to get a better dockerhub repo name. Right now publishing to https://hub.docker.com/r/getmovement/national-voter-file/
