### ISSUE TITLE
Reconcile Data Dictionary to OSDI Person record

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#217]
# Problem

We have a [data dictionary](https://docs.google.com/spreadsheets/d/1TcxEItYyThV9l6IK5xfdOCgXsGUkiBO-ecqJ078viog/edit?usp=sharing) that is somewhat out of date. It needs to be reconciled to the current database schema.

We will be providing our data as an [OSDI `people` object](https://opensupporter.github.io/osdi-docs/people.html).

## Subtasks
- [ ] Reconcile and update [data dictionary](https://docs.google.com/spreadsheets/d/1TcxEItYyThV9l6IK5xfdOCgXsGUkiBO-ecqJ078viog/edit?usp=sharing) to current database schema
- [ ] Reconcile data dictionary and map fields (where they exist) to the OSDI People object
- [ ] Suggest enhancements to our database
