### ISSUE TITLE
Create AWS Batch Pipeline for loading new files

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#219]
# Problem
The process for loading a voter file is manual and requires a linux VM to run. AWS offers a [batch system](https://aws.amazon.com/batch/) to run containerized jobs on a cluster from a job queue.

Migrate our process to this environment and trigger it from the upload of a file to S3.

## Subtasks
- [ ] Create process to build stand-alone docker image when code changes
- [ ] Engineer AWS Batch compute environment
- [ ] Engineer AWS Batch jobs
- [ ] Externalize database connection information for pentao so it can be set inside each job container
- [ ] Create Lambda trigger 
- [ ] Assemble steps into job

## References

Progress on: #
#210

**Comment by BenGalewsky** [comment]
Just about have this done. Need to complete the individual jobs for each step, but the basic engineering is done.
