### ISSUE TITLE
Create NVF AWS Account

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#220]
# Problem

We need a central AWS account for all NWS account that is funded by donations and grants. We will grant access to NVF project members to engineer solutions and use it to run the database, voter file pipeline, geocoder, and API
## Subtasks
- [ ] Create AWS Account
- [ ] Create IAM users
- [ ] Spin up Production postgres RDS instance
- [ ] Populate initial data

## References

Progress on: #
