### ISSUE TITLE
Allocate households to jurisdictions

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#222]
# Problem

We need accurate allocation of households to various jurisdictions and boundaries. The voter file data for this is unreliable. Once we geocode the households we can use shapefiles to allocate everyone.
## Subtasks
- [ ] Collect shapefiles for cenus blocks
- [ ] Collect shapefiles for NY precincts 
- [ ] Update tables to allocate households to census tract, census block, and precint

## References

Progress on: #
