### ISSUE TITLE
API Key Strategy

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#225]
# Problem

To protect the integrity of our system we need to be able to assign API keys to users of the voter registry KPI interface. 

## Subtasks
- [ ] Determine how to store, reference and manage keys
- [ ] Create process to generate keys for new customers
- [ ] Create process to revoke keys in the case of violations of terms of use

## References

Progress on: #
